server:
  port: 8082
orchestrator:
  pipelines:
    - name: rinf
      input:
        name: Ldio:LdesClient
        config:
          urls:
          - https://era.ilabt.imec.be/rinf/ldes
          source-format: text/turtle
          materialisation:
            enabled: false
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
            named-graph: http://rinf
        - name: Ldio:HttpOut
          config:
            rdf-writer:
              content-type: application/n-quads
            endpoint: http://host.docker.internal:8084/api/rinf/members